applications:
  - name: comments-api-dev
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/aristidesneto/comments-api-dev.git
      targetRevision: HEAD
      path: .
    destination:
      server: https://kubernetes.default.svc
      namespace: api-dev
    syncPolicy:
      automated:
        prune: false
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
