name: Deploy on Develop

on:
  push:
    branches: ["main", "develop"]

env:
  PROJECT_ID: "${{ secrets.GCP_PROJECT_ID }}"
  REGION: "${{ secrets.GCP_REGION }}"
  REGISTRY: "${{ secrets.GCP_REGISTRY }}"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract branch name
        id: current_branch
        run: |-
          branch_name=${GITHUB_REF#refs/heads/}
          echo "##[set-output name=branch_name]${branch_name}"

      - name: GCP authentication
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Docker build
        run: |-
          make build

      - name: Docker push
        run: |-
          make push

      - name: Update k8s files
        run: |-
          branch_name=$(echo ${{ current-branch.outputs.branch_name }})
          echo "The branch name is $branch_name"

  # sonarqube:

  # vulnerability_scan:
